package proxyapis

import (
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"

	"github.com/aniket0951/testproject/models"
)

type ProxyAPIRequest interface {
	GetAllVehicels(apiendpoint string) models.AutoGenerated
}

func GetAllVehicels(apiendpoint string, channel chan models.AutoGenerated) {
	resp, err := http.Get(apiendpoint)
	if err != nil {
		channel <- models.AutoGenerated{}
	}
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {
			fmt.Println(err)
		}
	}(resp.Body)
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		channel <- models.AutoGenerated{}
	}
	content := string(body)
	var jsonMap models.AutoGenerated
	_ = json.Unmarshal([]byte(content), &jsonMap)
	channel <- jsonMap
	close(channel)
}
