package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Vehicles struct {
	Id       primitive.ObjectID `json:"id,omitempty" bson:"_id"`
	VName    string             `json:"vehicle_name" bson:"v_name"`
	VNumber  string             `json:"vehicle_number" bson:"v_number"`
	VColor   string             `json:"vehicle_color" bson:"v_color"`
	VType    string             `json:"vehicle_type" bson:"v_type"`
	UserID   primitive.ObjectID `json:"userid" bson:"userid"`
	CreateAt time.Time          `json:"create_at" bson:"create_at"`
	UpdateAt time.Time          `json:"update_at" bson:"update_at"`
}

type VehiclesData struct {
	Id                primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	VehicleName       string             `json:"Vehicle_Name,omitempty" bson:"vehiclename"`
	Company           string             `json:"Company,omitempty" bson:"company"`
	Temperature       string             `json:"Temperature,omitempty" bson:"temperature"`
	Latitude          string             `json:"Latitude,omitempty" bson:"latitude"`
	GPS               string             `json:"GPS,omitempty" bson:"gps"`
	VehicleNo         string             `json:"Vehicle_No,omitempty" bson:"vehicleno"`
	Door1             string             `json:"Door1,omitempty" bson:"door1"`
	Door4             string             `json:"Door4,omitempty" bson:"door4"`
	Branch            string             `json:"Branch,omitempty" bson:"branch"`
	Vehicletype       string             `json:"Vehicletype,omitempty" bson:"vehicletype"`
	Door2             string             `json:"Door2,omitempty" bson:"door2"`
	Door3             string             `json:"Door3,omitempty" bson:"door3"`
	GPSActualTime     string             `json:"GPSActualTime,omitempty" bson:"gpsactualtime"`
	Datetime          string             `json:"Datetime,omitempty" bson:"datetime"`
	Status            string             `json:"Status,omitempty" bson:"status"`
	DeviceModel       string             `json:"DeviceModel,omitempty" bson:"devicemodel"`
	Speed             string             `json:"Speed,omitempty" bson:"speed"`
	AC                string             `json:"AC,omitempty" bson:"ac"`
	Imeino            string             `json:"Imeino,omitempty" bson:"imeino"`
	Odometer          string             `json:"Odometer,omitempty" bson:"odometer"`
	POI               string             `json:"POI,omitempty" bson:"poi"`
	DriverMiddleName  string             `json:"Driver_Middle_Name,omitempty" bson:"drivermiddlename"`
	Longitude         string             `json:"Longitude,omitempty" bson:"longitude"`
	ImmobilizeState   string             `json:"Immobilize_State,omitempty" bson:"immobilizestate"`
	IGN               string             `json:"IGN,omitempty" bson:"ign"`
	DriverFirstName   string             `json:"Driver_First_Name,omitempty" bson:"driverfirstname"`
	Angle             string             `json:"Angle,omitempty" bson:"angle"`
	SOS               string             `json:"SOS,omitempty" bson:"sos"`
	Fuel              []interface{}      `json:"Fuel,omitempty" bson:"fuel"`
	BatteryPercentage string             `json:"battery_percentage,omitempty" bson:"batterypercentage"`
	ExternalVolt      string             `json:"ExternalVolt,omitempty" bson:"externalvolt"`
	DriverLastName    string             `json:"Driver_Last_Name,omitempty" bson:"driverlastname"`
	Power             string             `json:"Power,omitempty" bson:"power"`
	Location          string             `json:"Location,omitempty" bson:"location"`
	TimeStamp         primitive.DateTime `json:"timeStamp" bson:"timeStamp"`
	CreatedAt         time.Time          `bson:"createdAt" json:"createdAt"`
	UpdatedAt         time.Time          `bson:"updatedAt" json:"updatedAt"`
}
type AutoGenerated struct {
	Root struct {
		VehicleData []struct {
			VehicleName       string        `json:"Vehicle_Name"`
			Company           string        `json:"Company"`
			Temperature       string        `json:"Temperature"`
			Latitude          string        `json:"Latitude"`
			GPS               string        `json:"GPS"`
			VehicleNo         string        `json:"Vehicle_No"`
			Door1             string        `json:"Door1"`
			Door4             string        `json:"Door4"`
			Branch            string        `json:"Branch"`
			Vehicletype       string        `json:"Vehicletype"`
			Door2             string        `json:"Door2"`
			Door3             string        `json:"Door3"`
			GPSActualTime     string        `json:"GPSActualTime"`
			Datetime          string        `json:"Datetime"`
			Status            string        `json:"Status"`
			DeviceModel       string        `json:"DeviceModel"`
			Speed             string        `json:"Speed"`
			AC                string        `json:"AC"`
			Imeino            string        `json:"Imeino"`
			Odometer          string        `json:"Odometer"`
			POI               string        `json:"POI"`
			DriverMiddleName  string        `json:"Driver_Middle_Name"`
			Longitude         string        `json:"Longitude"`
			ImmobilizeState   string        `json:"Immobilize_State"`
			IGN               string        `json:"IGN"`
			DriverFirstName   string        `json:"Driver_First_Name"`
			Angle             string        `json:"Angle"`
			SOS               string        `json:"SOS"`
			Fuel              []interface{} `json:"Fuel"`
			BatteryPercentage string        `json:"battery_percentage"`
			ExternalVolt      string        `json:"ExternalVolt"`
			DriverLastName    string        `json:"Driver_Last_Name"`
			Power             string        `json:"Power"`
			Location          string        `json:"Location"`
		} `json:"VehicleData"`
	} `json:"root"`
}

type VehicleInformation struct {
	Id                primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	VehicleName       string             `json:"Vehicle_Name,omitempty" bson:"vehiclename"`
	Company           string             `json:"Company,omitempty" bson:"company"`
	Temperature       string             `json:"Temperature,omitempty" bson:"temperature"`
	Latitude          string             `json:"Latitude,omitempty" bson:"latitude"`
	GPS               string             `json:"GPS,omitempty" bson:"gps"`
	VehicleNo         string             `json:"Vehicle_No,omitempty" bson:"vehicleno"`
	Door1             string             `json:"Door1,omitempty" bson:"door1"`
	Door4             string             `json:"Door4,omitempty" bson:"door4"`
	Branch            string             `json:"Branch,omitempty" bson:"branch"`
	Vehicletype       string             `json:"Vehicletype,omitempty" bson:"vehicletype"`
	Door2             string             `json:"Door2,omitempty" bson:"door2"`
	Door3             string             `json:"Door3,omitempty" bson:"door3"`
	GPSActualTime     string             `json:"GPSActualTime,omitempty" bson:"gpsactualtime"`
	Datetime          string             `json:"Datetime,omitempty" bson:"datetime"`
	Status            string             `json:"Status,omitempty" bson:"status"`
	DeviceModel       string             `json:"DeviceModel,omitempty" bson:"devicemodel"`
	Speed             string             `json:"Speed,omitempty" bson:"speed"`
	AC                string             `json:"AC,omitempty" bson:"ac"`
	Imeino            string             `json:"Imeino,omitempty" bson:"imeino"`
	Odometer          string             `json:"Odometer,omitempty" bson:"odometer"`
	POI               string             `json:"POI,omitempty" bson:"poi"`
	DriverMiddleName  string             `json:"Driver_Middle_Name,omitempty" bson:"drivermiddlename"`
	Longitude         string             `json:"Longitude,omitempty" bson:"longitude"`
	ImmobilizeState   string             `json:"Immobilize_State,omitempty" bson:"immobilizestate"`
	IGN               string             `json:"IGN,omitempty" bson:"ign"`
	DriverFirstName   string             `json:"Driver_First_Name,omitempty" bson:"driverfirstname"`
	Angle             string             `json:"Angle,omitempty" bson:"angle"`
	SOS               string             `json:"SOS,omitempty" bson:"sos"`
	Fuel              []interface{}      `json:"Fuel,omitempty" bson:"fuel"`
	BatteryPercentage string             `json:"battery_percentage,omitempty" bson:"batterypercentage"`
	ExternalVolt      string             `json:"ExternalVolt,omitempty" bson:"externalvolt"`
	DriverLastName    string             `json:"Driver_Last_Name,omitempty" bson:"driverlastname"`
	Power             string             `json:"Power,omitempty" bson:"power"`
	Location          string             `json:"Location,omitempty" bson:"location"`
	CreatedAt         time.Time          `bson:"createdAt" json:"createdAt"`
	UpdatedAt         time.Time          `bson:"updatedAt" json:"updatedAt"`
}

type VehicleLocationData struct {
	Id        primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	VehicleNo string             `json:"Vehicle_No,omitempty" bson:"vehicleno"`
	Latitude  string             `json:"Latitude,omitempty" bson:"latitude"`
	Longitude string             `json:"Longitude,omitempty" bson:"longitude"`
	Location  string             `json:"Location,omitempty" bson:"location"`
	CreatedAt time.Time          `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time          `json:"updated_at" bson:"updated_at"`
}

type VehicleAlerts struct {
	Id           primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
	BikeNo       string             `json:"bike_no" bson:"bike_no"`
	AlertCount   int64              `json:"alert_count" bson:"alert_count"`
	BikeSpeed    int64              `json:"bike_speed" bson:"bike_speed"`
	CreateAt     primitive.DateTime `json:"create_at" bson:"create_at"`
	UpdateAt     primitive.DateTime `json:"update_at" bson:"update_at"`
	ISTTimeStamp string             `json:"ist_timestamp" bson:"ist_timestamp"`
}

type VehicleFallAlerts struct {
	Id           primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
	BikeNo       string             `json:"bike_no" bson:"bike_no"`
	AlertCount   int64              `json:"alert_count" bson:"alert_count"`
	BikeAngle    string             `json:"bike_angle" bson:"bike_angle"`
	CreateAt     primitive.DateTime `json:"create_at" bson:"create_at"`
	UpdateAt     primitive.DateTime `json:"update_at" bson:"update_at"`
	ISTTimeStamp string             `json:"ist_timestamp" bson:"ist_timestamp"`
}

type VehicleAlertHistory struct {
	Id               primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
	BikeNo           string             `json:"bike_no" bson:"bike_no"`
	AlertCount       int64              `json:"alert_count" bson:"alert_count"`
	BikeSpeed        int64              `json:"bike_speed" bson:"bike_speed"`
	AlertType        string             `json:"alert_type" bson:"alert_type"`
	CreateAt         primitive.DateTime `json:"create_at" bson:"create_at"`
	UpdateAt         primitive.DateTime `json:"update_at" bson:"update_at"`
	ISTTimeStamp     string             `json:"ist_timestamp" bson:"ist_timestamp"`
	HistoryTimestamp primitive.DateTime `json:"history_timestamp" bson:"history_timestamp"`
}

type VehicleFallAlertHistory struct {
	Id               primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
	BikeNo           string             `json:"bike_no" bson:"bike_no"`
	AlertCount       int64              `json:"alert_count" bson:"alert_count"`
	BikeAngle        string             `json:"bike_angle" bson:"bike_angle"`
	AlertType        string             `json:"alert_type" bson:"alert_type"`
	CreateAt         primitive.DateTime `json:"create_at" bson:"create_at"`
	UpdateAt         primitive.DateTime `json:"update_at" bson:"update_at"`
	ISTTimeStamp     string             `json:"ist_timestamp" bson:"ist_timestamp"`
	HistoryTimestamp primitive.DateTime `json:"history_timestamp" bson:"history_timestamp"`
}

type AlertConfig struct {
	Id          primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	AlertType   string             `json:"alert_type" bson:"alert_type"`
	Description string             `json:"description" bson:"description"`
	Limit       int64              `json:"limit" bson:"limit"`
	CreatedAt   primitive.DateTime `json:"createdAt" bson:"created_at"`
	UpdatedAt   primitive.DateTime `json:"updatedAt" bson:"updated_at"`
}
